---
- name: Deploy web server nginx on docker using ansible for dev environment
  hosts: dev
  become: true
  tasks:
    
  - name: Start the container
    docker_container:
      name: happyit
      image: web2
      state: started
      published_ports:
        - 0.0.0.0:80:80

  - name: check status
    command:
      cmd: netstat -an | grep 80
    register: result
      
  - name: show result on screen 
    debug: var=result.stdout_lines
...

